export const CurentConversationTypes = {
  SWITCH_CURRENT_CONVERSATION: "SWITCH_CURRENT_CONVERSATION",
  GET_CURRENT_CONVERSATION_MESSAGES_START:
    "GET_CURRENT_CONVERSATION_MESSAGES_START",
  GET_CURRENT_CONVERSATION_MESSAGES_SUCCESS:
    "GET_CURRENT_CONVERSATION_MESSAGES_SUCCESS",
  GET_CURRENT_CONVERSATION_MESSAGES_FAILURE:
    "GET_CURRENT_CONVERSATION_MESSAGES_FAILURE",
};
