import { FriendsActionTypesInterface } from "../interfaces";

export const FriendsActionTypes: FriendsActionTypesInterface = {
  COVERT_SNAPSHOT_TO_USER_FRIENDS_START:
    "COVERT_SNAPSHOT_TO_USER_FRIENDS_START",
  COVERT_SNAPSHOT_TO_USER_FRIENDS_SUCCESS:
    "COVERT_SNAPSHOT_TO_USER_FRIENDS_SUCCESS",
  COVERT_SNAPSHOT_TO_USER_FRIENDS_FAILURE:
    "COVERT_SNAPSHOT_TO_USER_FRIENDS_FAILURE",
};
